package core.entities

/**
  * Represents a Token
  */
abstract class Token

/**
  * Represents a Token which is being used for authentication purpose
  */
abstract class AuthToken extends Token

/**
  * An authentication token as type of OAuth BearerToken
  *
  * @param token Token value
  */
case class BearerToken(token: String) extends AuthToken

/**
  * A Token generated by SecuredRandom
  *
  * @param token Token value
  */
case class SecuredToken(token: Array[Byte]) extends Token

/**
  * Current authenticated user sessionId
  * @param value SessionID value
  */
case class SessionID(value: String)

/**
  * A user context for authentication
  *
  * @param userId   Represented UserID
  * @param username Represents user name
  */
case class AuthTokenContext(userId: UserID, username: String)

/**
  * A user context for authentication
  *
  * @param userId   Represented UserID
  * @param username Represents user name
  * @param sessionId Represents a onetime claim value
  */
case class AuthTokenClaims(userId: UserID, username: String, sessionId: SessionID)
